apiVersion: v1
kind: Pod
metadata:
  generateName: hms-
  labels:
    app: hive-metastore
  namespace: emr
spec:
  containers:
  - name: hms
    #replace it by your docker image url
    image: ghcr.io/melodyyangaws/hive-metastore:3.0.0
    resources:
      limits:
        cpu: "1"
        memory: "1000Mi"
      requests:
        memory: "500Mi"
        cpu: "400m"
    command: ["sh", "-c", "/opt/hive-metastore/bin/entrypoint.sh & /bin/self-terminate.sh /var/log/fluentd/main-container-terminated"]
    env:
    - name: HIVE_DB_DRIVER
      value: com.mysql.cj.jdbc.Driver
    - name: HIVE_DB_EXTERNAL
      value: "true"
    # hard code Hive metastore RDS credentials  
    # - name: HIVE_DB_USER
    #   value: admin 
    # - name: HIVE_DB_PASS
    #   value: YOUR_PASSWORD
    # - name: HIVE_DB_HOST
    #   value: YOUR_RDS_HOST
    # - name: HIVE_DB_PORT
    #   value: "3306"
    # - name: HIVE_DB_NAME
    #   value: YOUR_DB_NAME
    # - name: HIVE_WAREHOUSE_S3LOCATION
    #   value: s3://YOUR_HMS_DWH        
    - name: HIVE_DB_USER
      valueFrom:
        secretKeyRef:
          name: rds-hms-secret
          key: username   
    - name: HIVE_DB_PASS
      valueFrom:
        secretKeyRef:
          name: rds-hms-secret
          key: password    
    - name: HIVE_DB_HOST
      valueFrom:
        secretKeyRef:
          name: rds-hms-secret
          key: host  
    - name: HIVE_DB_PORT
      valueFrom:
        secretKeyRef:
          name: rds-hms-secret
          key: port  
    - name: HIVE_DB_NAME
      valueFrom:
        secretKeyRef:
          name: rds-hms-secret
          key: dbname        
    volumeMounts:
    - name: hive-conf-templates
      mountPath: /opt/hive-metastore/conf/templates
    - name: sidecar-terminate-script
      mountPath: /bin/self-terminate.sh
      readOnly: true
      subPath: self-terminate.sh
    - name: emr-container-communicate
      mountPath: /var/log/fluentd
      readOnly: false

  restartPolicy: Never
  volumes:
  - name: hive-conf-templates 
    configMap:
      defaultMode: 420
      name: sidecar-hms-conf-templates
  - name: sidecar-terminate-script
    configMap:
      defaultMode: 448
      name: sidecar-terminate-script   