# image:
#   tag: v1beta2-1.2.3-3.1.1
serviceAccounts:
  # create IRSA for Spark app on our own, don't create Spark SA here.
  spark:
    create: false
  sparkoperator:
    create: true  
metrics:
# -- Disable prometheus metric scraping
  enable: false
webhook:
  enable: true